In [ ]:
# Q1
# arr = np.array([2, 4, 6])
# # Double all values (no loop)

# Q2
# arr = np.array([5, 15, 25, 35])
# # Get values > 20

# Q3
# arr = np.arange(1, 7)
# # Convert into shape (2, 3)

# Q4
# A = np.array([[1, 2],
#               [3, 4]])
# # Find column-wise sum

# Q5
# A = np.array([[10, 20],
#               [30, 40]])
# # Find row-wise mean

# Q6
# A = np.array([[1, 2],
#               [3, 4]])

# B = np.array([[5, 6],
#               [7, 8]])

# # Concatenate column-wise

# Q7
# A = np.array([[1, 2, 3, 4],
#               [5, 6, 7, 8]])

# # Split into 2 column blocks

# Q8
# A = np.array([[1, 2],
#               [3, 4]])

# # Flatten this array

# Q9
# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
# # Dot product (manual answer + numpy)

In [ ]:
# A1
# arr * 2

# A2
# arr[arr > 20]

# A3
# arr.reshape(2, 3)

# A4
# np.sum(A, axis=0)

# A5
# np.mean(A, axis=1)

# A6
# np.concatenate([A, B], axis=1)

# A7
# np.split(A, 2, axis=1)

# A8
# A.flatten()

# A9
# Manual:
# (1×4) + (2×5) + (3×6)
# = 4 + 10 + 18 = 32

# NumPy:
# np.dot(a, b)
# # or
# a @ b

In [ ]:
import numpy as np

arr_1d = np.array([1,2,3,4,5])
print(np.sum(arr_1d))

print(np.mean(arr_1d))

print(np.min(arr_1d))

print(np.max(arr_1d))

print(np.sqrt(arr_1d)) # square root!

print(np.std(arr_1d))

print(np.var(arr_1d))




15
3.0
1
5
[1.         1.41421356 1.73205081 2.         2.23606798]
1.4142135623730951
2.0


In [ ]:
arr = np.array([10,20,30,40,50])

new = arr > 25
new # Masking
# 1. F F T T T --> CORRECT!!
# 2. Actual numbers > 25?

array([False, False,  True,  True,  True])

In [ ]:
arr[arr>25]


array([30, 40, 50])

In [ ]:
print(arr)
print(arr + 10) # vectorization

[10 20 30 40 50]
[20 30 40 50 60]


In [ ]:
n_arr = np.array([1,10,100,1000,10000,100000])

n_arr.ndim


1

In [ ]:
n_arr.shape

(6,)

In [ ]:
n_arr.size

6

In [ ]:
# reshape this array?
# 2x3 -> 6 elements
# 3x2 -> 6 elements
# 4x4 -> NO , number of elements will be a mismatch

n_arr


array([     1,     10,    100,   1000,  10000, 100000])

In [ ]:
n_arr.reshape(2,3)

array([[     1,     10,    100],
       [  1000,  10000, 100000]])

In [ ]:
n_arr.reshape(3,2)

array([[     1,     10],
       [   100,   1000],
       [ 10000, 100000]])

In [ ]:
n_arr.reshape(1,6)

array([[     1,     10,    100,   1000,  10000, 100000]])

In [ ]:
n_arr.reshape(6,1)

array([[     1],
       [    10],
       [   100],
       [  1000],
       [ 10000],
       [100000]])

In [ ]:
n_arr.reshape(4,4)

ValueError: cannot reshape array of size 6 into shape (4,4)

In [ ]:
arr_2d = np.array([[1, 2, 3],
              [4, 5, 6]])

arr_2d.ndim

2

In [ ]:
arr_2d.flatten() # will change the dimension to 1d

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

print(np.concatenate([a,b]))


[1 2 3 4]


In [ ]:
"a" + "b"

'ab'

In [ ]:
a1 = np.array([[1, 2],
              [3, 4]])

b1 = np.array([[5, 6]])

# axis = 0 -> stack row wise
print(np.concatenate([a1,b1], axis = 0))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


result = np.concatenate([A, B], axis=1)
result
# 1.yes -> output
# 2. no -> reason

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
result = np.concatenate([A, B], axis=0)
result
# 1.yes -> output
# 2. no -> reason

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr = np.array([1,2,3,4,5,6])

np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
arr = np.array([1,2,3,4,5,6,7])

np.split(arr,3)

ValueError: array split does not result in an equal division

In [ ]:
arr2 = np.array([[1, 2],
              [3, 4]])
np.split(arr2,2,axis =0)
# 1. yes -> output?
# 2.  no -> reason?

[array([[1, 2]]), array([[3, 4]])]

In [ ]:
np.split(arr2,2,axis = 1)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [ ]:
np.split(arr2,2) # default axis = 0

[array([[1, 2]]), array([[3, 4]])]

In [ ]:
# Dot product :
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# dot product : (1*4) + (2*5) + (3*6) = 4 + 10 + 18 = 32

print(np.dot(a,b))

32


In [ ]:
print(a @ b)

32


In [ ]:
a2 = np.array([[1, 2],
     [3, 4]])

b2 = np.array([[5, 6],
     [7, 8]])


# First row of a2 x first column of b2
# (1*5) + (2*7) = 19
# First row of a2 x second col of b2
# (1*6) + (2*8) = 22

# Second row of a2 x first column of b2
# (3*5) + (4*7) = 43
# Second row of a2 x second column of b2
# (3*6) + (4*8) = 50
print(a2 @ b2)


[[19 22]
 [43 50]]


In [ ]:
# Random arrays!
data = np.random.rand(5) # 5 elements between 0 and 1
data

data = np.random.rand(2,3)
data

array([[0.39023202, 0.05598854, 0.638832  ],
       [0.0023793 , 0.12356796, 0.9526958 ]])

In [ ]:
data = np.random.randint(1,100,5)
data
# 1 -> lower
# 100 ->  upper
# 5 -> 5 random integerts between lower and upper bound!

array([28, 96, 36, 43, 60])

In [ ]:
np.random.randint(1,100,(2,3))

array([[ 9, 40, 31],
       [44, 66, 60]])

In [ ]:
flat = np.array([0.01, 0.14, 0.09, 0.88, 0.94, 0.72])
# 6 elements

In [ ]:
print(np.argmax(flat))
# index of max element of the array

4


In [ ]:
print(np.argmin(flat))
# index of min element of the array

0
