In [ ]:
# Numpy : is a library which is used for numerical computations in python.

# Why numpy is needed?
# NumPy --> NumPy array :
# a. Extremely fast
# b. Memory efficient
# c. Built for numerical operations

# Python lists are general purpose, NumPy arrays are built for Maths

In [ ]:
# What is an array?
# Array = collection of value stored in a structured format. (similar to matrix)

In [ ]:
import numpy as np
# import pandas as pd

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# 1d array = simple list-like structure

In [ ]:
arr.ndim # 1 = 1d array!

1

In [ ]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2.ndim

# rows and columns --> data we'll be working on!

2

In [ ]:
# 1d array --> Vector
# 2d array --> Matrix
# 3d+ array -> Tensors

In [ ]:
# Array Properties!

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.shape
# 2,3 --> 2 rows, 3 columns

(2, 3)

In [ ]:
arr2.ndim
# dimensions of the array!

2

In [ ]:
arr2.size
# number of elements in the array

6

In [ ]:
arr2.dtype
# datatype of the value stored inside the array

dtype('int64')

In [ ]:
arr3 = np.array([1,2,3])
arr3

array([1, 2, 3])

In [ ]:
arr3 + 10
# 1. a single element
# 2. all elements --> ALL!

array([11, 12, 13])

In [ ]:
arr3*2

array([2, 4, 6])

In [ ]:
# Operations happen on entire array (vectorized)

In [ ]:
# Compares the performance of a list v/s array!

In [ ]:
import time
lst = list(range(1000000))
start = time.time()
lst = [x * 2 for x in lst]
end = time.time()
print("List time:", end - start)

List time: 0.17492127418518066


In [ ]:
import time
arr = np.arange(1000000)
start = time.time()
arr = arr * 2
end = time.time()
print("NumPy time:", end - start)

NumPy time: 0.004155397415161133


In [ ]:
# ipynb : interactive python notebook!

In [ ]:
# Indexing, slicing

In [ ]:
arr3

array([1, 2, 3])

In [ ]:
arr3[0] # 0th index --> 1st element

np.int64(1)

In [ ]:
arr3[-1]
# last element

np.int64(3)

In [ ]:
arr3

array([1, 2, 3])

In [ ]:
arr3[0:2]
# Start at 0th index, go till 2nd index (not incl)
# 0 and 1 index --> 1 and 2 element in the output

array([1, 2])

In [ ]:
# Q1 :

In [ ]:
lst = [10,0,6,11,19,0,100,0,0,1]
# 1. shift all the 0s towards the end of the list
# 2. order of non zero elements should not change
# Output : [10,6,11,19,100,1,0,0,0,0]

In [ ]:
zero    = []
nonzero = []
for i in lst :
  if i == 0 :
    zero.append(i)
  else :
    nonzero.append(i)

In [ ]:
zero

[0, 0, 0, 0]

In [ ]:
nonzero

[10, 6, 11, 19, 100, 1]

In [ ]:
nonzero + zero

[10, 6, 11, 19, 100, 1, 0, 0, 0, 0]

In [ ]:
# Q. Write a program to print numbers from 1 to 20 with the following rules:
# If number is even → print "Even"
# If number is odd → print "Odd"
# If divisible by both 2 and 3 → print "EvenThree"
# Else print the number

In [ ]:
for i in range(1,21) :
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [ ]:
for i in range(1,21) :
  if i % 2 ==0 and i % 3 == 0 :
    print(i,"-","EvenThree")
  elif i % 2 == 0 :
    print(i,"-","Even")
  elif i % 2 != 0 :
    print(i,"-","Odd")
  else :
    print(i)

1 - Odd
2 - Even
3 - Odd
4 - Even
5 - Odd
6 - EvenThree
7 - Odd
8 - Even
9 - Odd
10 - Even
11 - Odd
12 - EvenThree
13 - Odd
14 - Even
15 - Odd
16 - Even
17 - Odd
18 - EvenThree
19 - Odd
20 - Even


In [ ]:
# HW1 :
# Write a func!
# Given an integer x,
# return x with its digits reversed

# Example 1:
x = 123
# ●	Output: 321

# Example 2:
x = -123
# ●	Output: -321

In [ ]:
# HW2 :
x = [1,2,3,100,100,100,99,98,97]
# find 2nd largest number of the list
# without using sets
# o/p : 99

In [ ]:
 # HW3 :
 products = [(100, 5), (80, 10), (200, 15), (50, 7)]

# [(price,quantity),(price,quantity),.....]

# quantity >= 10 , 20% discount
# quantity < 10  , no discount

# o/p : [500,640,2400,350]

In [ ]:
# HW4 :
dct = {1:"data",2:"science"}
# Reverse its k:v pairs :
# o/p : {"data":1, "science":2}

In [ ]:
# HW5 :
# Dictionaries and Functions: Write a function update_scores
# that takes a dictionary containing player names and their scores,
#     and a list of tuples where each tuple contains a
#     player's name and points to add to their score.

player_scores = {'Alice': 10,   'Bob': 8,  'Carol': 15}
updates       = [('Alice', 5), ('Bob', 2), ('Dave', 7)]

# O/P : {'Alice': 15, 'Bob': 10, 'Carol': 15, 'Dave': 7}

In [ ]:
# Numpy :

In [ ]:
# HW6 :
# Q1. What is the main purpose of NumPy?
# A. Web development
# B. Numerical computing
# C. Database management
# D. UI design

# Q2. What does arr.shape return?
# A. Total elements
# B. Data type
# C. Dimensions (rows, columns)
# D. Memory size

# Q3. What will be the output?
# import numpy as np
# arr = np.array([1, 2, 3])
# print(arr * 2)
# A. [1, 2, 3, 2, 4, 6]
# B. [2, 4, 6]
# C. Error
# D. [1, 4, 9]

# Q4. Why is NumPy faster than Python lists?
# A. Uses Python loops
# B. Uses C-level optimized operations
# C. Uses more memory
# D. Does not store data

# Q5. What is the dimension of this array?
# arr = np.array([[1, 2], [3, 4]])
# A. 1
# B. 2
# C. 3
# D. 4

In [ ]:
# HW7 :
# Create a NumPy array from 1 to 10 and print its shape, size, and data type.

In [ ]:
# HW8 :
# Create a NumPy array [10, 20, 30, 40] and:
# Multiply all elements by 3
# Add 5 to each element
# Print the result