In [ ]:
#NUMPY: IT IS A LIBRARY WHICH IS USED FOR NUMERICAL COMPUTATIONS IN PYTHON.

#WHY NUMPY IS NEEDED ?
""" NUMPY ---> NUMPY ARRAY:
EXTREMELY FAST
MEMEORY EFFECIENT
BUILT FOR NUMERICAL OPERATIONS.

PYTHON LISTS ARE GENERAL PURPOSE, NUMPY ARE BUILTS FOR MATHS

WHT IS ARRAY.. COLLECTION OF VALUE STORED IN A STRUCTURED FORMAT SIMILAR TO MATRIX
"""


In [ ]:
import numpy as np
arr = np.array([1,16,14,23])
print(arr)

[ 1 16 14 23]


In [ ]:
arr

array([ 1, 16, 14, 23])

In [ ]:
type(arr)
arr.ndim #1 = 1d array
#1D ARRAY= SIMPLE LIST-LIKE STRUCTURE

1

In [ ]:
arr2 = np.array([[1,2,3,4],[5,8,5,6]])
print(arr2)

[[1 2 3 4]
 [5 8 5 6]]


In [ ]:
arr2.ndim

#rows and columns data we will be working on..

2

In [ ]:
"""1d --> vectori
2d array --> matrices
3d array --> tensors

ARRAY PROPERTIES..

"""

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 8, 5, 6]])

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2.ndim #dimesnsion of array

2

In [ ]:
arr2.size #gives no. of elements in the array

8

In [ ]:
arr2.dtype #data type the value stored inside the array

dtype('int64')

In [ ]:
arr3 = np.array([34,56,78])
print(arr3)

[34 56 78]


In [ ]:
arr3 + 10
# 1. a single element
#2 . all elements --> all


array([44, 66, 88])

In [ ]:
arr3*2

#so when we are doing any operation it happens on entire array elements (vectorized)


array([ 68, 112, 156])

In [ ]:
#COMPARES LISTS VS ARRAY: PERFORMANCE..

import time
lst = list(range(100000))
start = time.time()
lst = [x * 2 for x in lst]
end = time.time()
print("List Time:", end - start)

List Time: 0.009639978408813477


In [ ]:
import time
arr = np.arange(100000)
start = time.time()
arr = arr * 2
end = time.time()
print("Numpy Time:", end - start)

Numpy Time: 0.00037217140197753906


In [ ]:
#indexing and slicing

arr3

array([34, 56, 78])

In [ ]:
arr[0] #oth index 1st element
#in python indexing starts from 0

np.int64(0)

In [ ]:
arr3[0:2]
#starts from 0th indec go till 2nd inde (not include)
#0 and 1 index --> 1 and 2 element in the o/p

array([34, 56])

In [ ]:
lst = [10,0,6,11,19,0,100,0,0,1]

#shift all zerores towards the end.
# order of non zero elements should not change

zero = []
nonzero = []
for i in lst:
  if i == 0:
    zero.append(i)
  else:
    nonzero.append(i)
print(nonzero + zero)

[10, 6, 11, 19, 100, 1, 0, 0, 0, 0]


In [ ]:
lst = [10,0,6,11,19,0,100,0,0,1]
non_zeros = []
zeros_count = 0
for element in lst:
  if element != 0:
   non_zeros.append(element)
  else:
    zeros_count +=1

  lst = non_zeros + [0] * zeros_count
  print(lst)


[10]
[10, 0]
[10, 6, 0]
[10, 6, 11, 0]
[10, 6, 11, 19, 0]
[10, 6, 11, 19, 0, 0]
[10, 6, 11, 19, 100, 0, 0]
[10, 6, 11, 19, 100, 0, 0, 0]
[10, 6, 11, 19, 100, 0, 0, 0, 0]
[10, 6, 11, 19, 100, 1, 0, 0, 0, 0]


In [ ]:
#write a program to print no from 1 to 20 with the folloing trules:
#if no. is even print even
#if no.is add print odd
# if divisble by both 2 d 3 print even three
#else: print he number.

lst = [1,2,3,4,5,6,7,8,9,10,11,12,1,3,14,15,16,17,18,19,20]
for element in lst:
  if element % 2 == 0:
  print("Even")
  elif element % == 3:
  print("Odd")
  elif element % == 2 or 3:
  print("Even three")
else:
   print("lst")


IndentationError: expected an indented block after 'if' statement on line 9 (1518456815.py, line 10)

In [ ]:
for i in range(1,21):
  if i % 2 == 0 and i % 3 == 0:
    print(i, "-", "Even Three")
  elif i % 2 == 0:
    print(i, "-", "Even")
  elif i % 2 != 0:
    print(i, "-", "odd")
  else:
    print(i)

1 - odd
2 - Even
3 - odd
4 - Even
5 - odd
6 - Even Three
7 - odd
8 - Even
9 - odd
10 - Even
11 - odd
12 - Even Three
13 - odd
14 - Even
15 - odd
16 - Even
17 - odd
18 - Even Three
19 - odd
20 - Even


In [ ]:
# HW1 :
# Write a func!
# Given an integer x,
# return x with its digits reversed

# Example 1:
x = 123
# ●	Output: 321

# Example 2:
x = -123
# ●	Output: -321


# HW2 :
x = [1,2,3,100,100,100,99,98,97]
# find 2nd largest number of the list
# without using sets
# o/p : 99

 # HW3 :
 #products = [(100, 5), (80, 10), (200, 15), (50, 7)]

# [(price,quantity),(price,quantity),.....]

# quantity >= 10 , 20% discount
# quantity < 10  , no discount

# o/p : [500,640,2400,350]

# HW4 :
#dct = {1:"data",2:"science"}
# Reverse its k:v pairs :
# o/p : {"data":1, "science":2}


# HW5 :
# Dictionaries and Functions: Write a function update_scores
# that takes a dictionary containing player names and their scores,
#     and a list of tuples where each tuple contains a
#     player's name and points to add to their score.

#player_scores = {'Alice': 10,   'Bob': 8,  'Carol': 15}
#updates       = [('Alice', 5), ('Bob', 2), ('Dave', 7)]

# O/P : {'Alice': 15, 'Bob': 10, 'Carol': 15, 'Dave': 7}

# HW6 :
# Q1. What is the main purpose of NumPy?
# A. Web development
# B. Numerical computing
# C. Database management
# D. UI design

# Q2. What does arr.shape return?
# A. Total elements
# B. Data type
# C. Dimensions (rows, columns)
# D. Memory size

# Q3. What will be the output?
# import numpy as np
# arr = np.array([1, 2, 3])
# print(arr * 2)
# A. [1, 2, 3, 2, 4, 6]
# B. [2, 4, 6]
# C. Error
# D. [1, 4, 9]

# Q4. Why is NumPy faster than Python lists?
# A. Uses Python loops
# B. Uses C-level optimized operations
# C. Uses more memory
# D. Does not store data

# Q5. What is the dimension of this array?
# arr = np.array([[1, 2], [3, 4]])
# A. 1
# B. 2
# C. 3
# D. 4



# HW7 :
# Create a NumPy array from 1 to 10 and print its shape, size, and data type.



# HW8 :
# Create a NumPy array [10, 20, 30, 40] and:
# Multiply all elements by 3
# Add 5 to each element
# Print the result

